# Site settings
author: Guosa Edebiri
title: In Search of Lost Code
header-img: img/home-bg.png
email: gedebiri@gmail.com
copyright_name: Guosa Edebiri
description: > # this means to ignore newlines until "baseurl:"
  A technology and software blog
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  GuosaE

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
